### SignUp 
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "name": "User7",
  "email": "user7@user7.com",
  "password": "user7"
}

### Login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "user@user.com",
  "password": "user"
}

### Add Product
POST http://localhost:8000/product/add
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmQ1ZjMxNWZmYjhjNTgyYTlhMDBjYiIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiX192IjowfSwiaWF0IjoxNjgwOTQxMDg5LCJleHAiOjE2ODA5NDgyODl9.oPrA9sSgRheopklE9EF2Q2oGJfUF7mh0tO01xXlN7JI
Content-Type: application/json

{
  "name": "Nokia Lumia",
  "price": "1000",
  "category": "mobile",
  "userId": "642da9cc2cbfec29577e4923",
  "company": "Nokia"
}

### Get All Products
GET http://localhost:8000/product/all
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmQ1ZjMxNWZmYjhjNTgyYTlhMDBjYiIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiX192IjowfSwiaWF0IjoxNjgwOTQxMDg5LCJleHAiOjE2ODA5NDgyODl9.oPrA9sSgRheopklE9EF2Q2oGJfUF7mh0tO01xXlN7JI

### Delete Product
DELETE http://localhost:8000/product/delete/642f00fc3a48fb10e05462c6

### GET Single Product by ID
GET http://localhost:8000/product/642e9c8a416dfabd73249df2

### Updata Product by ID
PUT http://localhost:8000/product/update/642e9c8a416dfabd73249df2
Content-Type: application/json

{
  "price": "450",
  "company": "Microsoft"
}

### Search Product
GET http://localhost:8000/product/search/o
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmQ1ZjMxNWZmYjhjNTgyYTlhMDBjYiIsIm5hbWUiOiJVc2VyIiwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwiX192IjowfSwiaWF0IjoxNjgwOTQxMDg5LCJleHAiOjE2ODA5NDgyODl9.oPrA9sSgRheopklE9EF2Q2oGJfUF7mh0tO01xXlN7JI
